In [27]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\nabee\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (7.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.0.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\nabee\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\nabee\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\nabee\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\nabee\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [28]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [29]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [30]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [31]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [32]:
X= df[['soil_moisture','temperature_c', 'sunlight_hours']]
Y = df['needs_water']

In [33]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/( X_max- X_min + 1e-8)

In [34]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, test_size=0.25, random_state=42)

In [36]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [37]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [42]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=2,verbose=1
)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.5646 - val_accuracy: 0.7500 - val_loss: 0.5977
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5645 - val_accuracy: 0.7500 - val_loss: 0.5962
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5630 - val_accuracy: 0.7500 - val_loss: 0.5957
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5616 - val_accuracy: 0.7500 - val_loss: 0.5951
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5613 - val_accuracy: 0.7500 - val_loss: 0.5945
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5605 - val_accuracy: 0.7500 - val_loss: 0.5937
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5585 - val_accuracy: 0.7500 - val_loss: 0.5931
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5582 - val_accuracy: 0.7500 - val_loss: 0.5913
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5563 - val_accuracy: 0.7500 - val_loss: 0.5906
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5560 - val_accuracy: 0.7500 - val_loss: 0.5899
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.5550 - val_accuracy: 0.7500 - val_loss: 0.5881
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.5538 - val_accuracy: 0.7500 - val_loss: 0.5864
Epoch 13/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5524 - val_accuracy: 0.7500 - val_loss: 0.5856
Epoch 14/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5523 - val_accuracy: 0.7500 - val_loss: 0.5848
Epoch 15/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5502 - val_accuracy: 0.7500 - val_loss: 0.5841
Epoch 16/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5490 - val_accuracy: 0.7500 - val_loss: 0.5832
Epoch 17/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.5506 - val_accuracy: 0.7500 - val_loss: 0.5825
Epoch 18/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5481 - val_accuracy: 0.7500 - val_loss: 0.5814
Epoch 19/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5476 - val_accuracy: 0.7500 - val_loss: 0.5806
Epoch 20/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.5460 - val_accuracy: 0.7500 - val_loss: 0.5798
Epoch 21/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5439 - val_accuracy: 0.7500 - val_loss: 0.5789
Epoch 22/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5442 - val_accuracy: 0.7500 - val_loss: 0.5779
Epoch 23/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5428 - val_accuracy: 0.7500 - val_loss: 0.5770
Epoch 24/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5433 - val_accuracy: 0.7500 - val_loss: 0.5760
Epoch 25/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5426 - val_accuracy: 0.7500 - val_loss: 0.5749
Epoch 26/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.5396 - val_accuracy: 0.7500 - val_loss: 0.5739
Epoch 27/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5392 - val_accuracy: 0.7500 - val_loss: 0.5728
Epoch 28/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5384 - val_accuracy: 0.7500 - val_loss: 0.5718
Epoch 29/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5356 - val_accuracy: 0.7500 - val_loss: 0.5708
Epoch 30/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5353 - val_accuracy: 0.7500 - val_loss: 0.5697
Epoch 31/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5340 - val_accuracy: 0.7500 - val_loss: 0.5687
Epoch 32/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5328 - val_accuracy: 0.7500 - val_loss: 0.5677
Epoch 33/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.5327 - val_accuracy: 0.7500 - val_loss: 0.5665
Epoch 34/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5313 - val_accuracy: 0.7500 - val_loss: 0.5654
Epoch 35/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5298 - val_accuracy: 0.7500 - val_loss: 0.5644
Epoch 36/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5283 - val_accuracy: 0.7500 - val_loss: 0.5632
Epoch 37/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5285 - val_accuracy: 0.7500 - val_loss: 0.5619
Epoch 38/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5272 - val_accuracy: 0.7500 - val_loss: 0.5609
Epoch 39/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5254 - val_accuracy: 0.7500 - val_loss: 0.5598
Epoch 40/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5250 - val_accuracy: 0.7500 - val_loss: 0.5586
Epoch 41/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5233 - val_accuracy: 0.7500 - val_loss: 0.5575
Epoch 42/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5216 - val_accuracy: 0.7500 - val_loss: 0.5565
Epoch 43/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5218 - val_accuracy: 0.7500 - val_loss: 0.5554
Epoch 44/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5202 - val_accuracy: 0.7500 - val_loss: 0.5544
Epoch 45/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5187 - val_accuracy: 0.7500 - val_loss: 0.5534
Epoch 46/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7500 - loss: 0.5172 - val_accuracy: 0.7500 - val_loss: 0.5525
Epoch 47/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.5170 - val_accuracy: 0.7500 - val_loss: 0.5516
Epoch 48/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5150 - val_accuracy: 0.7500 - val_loss: 0.5505
Epoch 49/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5149 - val_accuracy: 0.7500 - val_loss: 0.5495
Epoch 50/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5130 - val_accuracy: 0.7500 - val_loss: 0.5486
Epoch 51/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5131 - val_accuracy: 0.7500 - val_loss: 0.5475
Epoch 52/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7500 - loss: 0.5113 - val_accuracy: 0.7500 - val_loss: 0.5465
Epoch 53/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5123 - val_accuracy: 0.7500 - val_loss: 0.5452
Epoch 54/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.5097 - val_accuracy: 0.7500 - val_loss: 0.5440
Epoch 55/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.5075 - val_accuracy: 0.7500 - val_loss: 0.5429
Epoch 56/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5071 - val_accuracy: 0.7500 - val_loss: 0.5417
Epoch 57/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5053 - val_accuracy: 0.7500 - val_loss: 0.5408
Epoch 58/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.5053 - val_accuracy: 0.7500 - val_loss: 0.5397
Epoch 59/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.5035 - val_accuracy: 0.7500 - val_loss: 0.5386
Epoch 60/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5035 - val_accuracy: 0.7500 - val_loss: 0.5377
Epoch 61/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5024 - val_accuracy: 0.7500 - val_loss: 0.5365
Epoch 62/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5013 - val_accuracy: 0.7500 - val_loss: 0.5355
Epoch 63/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.5005 - val_accuracy: 0.7500 - val_loss: 0.5343
Epoch 64/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.4969 - val_accuracy: 0.7500 - val_loss: 0.5332
Epoch 65/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.4977 - val_accuracy: 0.7500 - val_loss: 0.5320
Epoch 66/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4965 - val_accuracy: 0.7500 - val_loss: 0.5311
Epoch 67/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4949 - val_accuracy: 0.7500 - val_loss: 0.5302
Epoch 68/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4933 - val_accuracy: 0.7500 - val_loss: 0.5292
Epoch 69/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4914 - val_accuracy: 0.7500 - val_loss: 0.5281
Epoch 70/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4917 - val_accuracy: 0.7500 - val_loss: 0.5271
Epoch 71/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4904 - val_accuracy: 0.7500 - val_loss: 0.5260
Epoch 72/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.4912 - val_accuracy: 0.7500 - val_loss: 0.5251
Epoch 73/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4876 - val_accuracy: 0.7500 - val_loss: 0.5240
Epoch 74/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4858 - val_accuracy: 0.7500 - val_loss: 0.5229
Epoch 75/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.4872 - val_accuracy: 0.7500 - val_loss: 0.5219
Epoch 76/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4849 - val_accuracy: 0.7500 - val_loss: 0.5210
Epoch 77/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4847 - val_accuracy: 0.7500 - val_loss: 0.5199
Epoch 78/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4813 - val_accuracy: 0.7500 - val_loss: 0.5188
Epoch 79/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4799 - val_accuracy: 0.7500 - val_loss: 0.5176
Epoch 80/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4817 - val_accuracy: 0.7500 - val_loss: 0.5166
Epoch 81/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.4796 - val_accuracy: 0.7500 - val_loss: 0.5155
Epoch 82/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4796 - val_accuracy: 0.7500 - val_loss: 0.5143
Epoch 83/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4763 - val_accuracy: 0.7500 - val_loss: 0.5134
Epoch 84/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.4754 - val_accuracy: 0.7500 - val_loss: 0.5124
Epoch 85/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4748 - val_accuracy: 0.7500 - val_loss: 0.5111
Epoch 86/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4750 - val_accuracy: 0.7500 - val_loss: 0.5099
Epoch 87/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4728 - val_accuracy: 0.7500 - val_loss: 0.5088
Epoch 88/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4723 - val_accuracy: 0.7500 - val_loss: 0.5077
Epoch 89/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.4691 - val_accuracy: 0.7500 - val_loss: 0.5066
Epoch 90/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4678 - val_accuracy: 0.7500 - val_loss: 0.5056
Epoch 91/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4667 - val_accuracy: 0.7500 - val_loss: 0.5044
Epoch 92/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4671 - val_accuracy: 0.7500 - val_loss: 0.5035
Epoch 93/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4653 - val_accuracy: 0.7500 - val_loss: 0.5026
Epoch 94/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4637 - val_accuracy: 0.7500 - val_loss: 0.5016
Epoch 95/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4638 - val_accuracy: 0.7500 - val_loss: 0.5002
Epoch 96/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4615 - val_accuracy: 0.7500 - val_loss: 0.4991
Epoch 97/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9167 - loss: 0.4617 - val_accuracy: 0.7500 - val_loss: 0.4980
Epoch 98/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4586 - val_accuracy: 0.7500 - val_loss: 0.4970
Epoch 99/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4595 - val_accuracy: 0.7500 - val_loss: 0.4961
Epoch 100/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.4573 - val_accuracy: 0.7500 - val_loss: 0.4949

### Full Batch Gradient Descent

In [43]:
history_full_batch = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=len(X_train),verbose=1
)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.9167 - loss: 0.4552 - val_accuracy: 0.7500 - val_loss: 0.4948
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.9167 - loss: 0.4550 - val_accuracy: 0.7500 - val_loss: 0.4946
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4548 - val_accuracy: 0.7500 - val_loss: 0.4944
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4547 - val_accuracy: 0.7500 - val_loss: 0.4942
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.9167 - loss: 0.4545 - val_accuracy: 0.7500 - val_loss: 0.4941
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4543 - val_accuracy: 0.7500 - val_loss: 0.4939
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.9167 - loss: 0.4541 - val_accuracy: 0.7500 - val_loss: 0.4937
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.9167 - loss: 0.4539 - val_accuracy: 0.7500 - val_loss: 0.4935
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.9167 - loss: 0.4537 - val_accuracy: 0.7500 - val_loss: 0.4934
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4535 - val_accuracy: 0.7500 - val_loss: 0.4932
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4534 - val_accuracy: 0.7500 - val_loss: 0.4930
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.9167 - loss: 0.4532 - val_accuracy: 0.7500 - val_loss: 0.4928
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.9167 - loss: 0.4530 - val_accuracy: 0.7500 - val_loss: 0.4927
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.9167 - loss: 0.4528 - val_accuracy: 0.7500 - val_loss: 0.4925
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4526 - val_accuracy: 0.7500 - val_loss: 0.4923
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4524 - val_accuracy: 0.7500 - val_loss: 0.4921
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.9167 - loss: 0.4522 - val_accuracy: 0.7500 - val_loss: 0.4920
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.9167 - loss: 0.4521 - val_accuracy: 0.7500 - val_loss: 0.4918
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4519 - val_accuracy: 0.7500 - val_loss: 0.4916
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4517 - val_accuracy: 0.7500 - val_loss: 0.4914
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4515 - val_accuracy: 0.7500 - val_loss: 0.4913
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4513 - val_accuracy: 0.7500 - val_loss: 0.4911
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4511 - val_accuracy: 0.7500 - val_loss: 0.4909
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4509 - val_accuracy: 0.7500 - val_loss: 0.4907
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4508 - val_accuracy: 0.7500 - val_loss: 0.4906
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4506 - val_accuracy: 0.7500 - val_loss: 0.4904
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4504 - val_accuracy: 0.7500 - val_loss: 0.4902
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4502 - val_accuracy: 0.7500 - val_loss: 0.4901
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4500 - val_accuracy: 0.7500 - val_loss: 0.4899
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4498 - val_accuracy: 0.7500 - val_loss: 0.4897
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.9167 - loss: 0.4496 - val_accuracy: 0.7500 - val_loss: 0.4895
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9167 - loss: 0.4495 - val_accuracy: 0.7500 - val_loss: 0.4894
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.9167 - loss: 0.4493 - val_accuracy: 0.7500 - val_loss: 0.4892
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4491 - val_accuracy: 0.7500 - val_loss: 0.4890
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 0.9167 - loss: 0.4489 - val_accuracy: 0.7500 - val_loss: 0.4888
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4487 - val_accuracy: 0.7500 - val_loss: 0.4887
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9167 - loss: 0.4485 - val_accuracy: 0.7500 - val_loss: 0.4885
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.9167 - loss: 0.4484 - val_accuracy: 0.7500 - val_loss: 0.4883
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4482 - val_accuracy: 0.7500 - val_loss: 0.4882
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4480 - val_accuracy: 0.7500 - val_loss: 0.4880
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4478 - val_accuracy: 0.7500 - val_loss: 0.4878
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4476 - val_accuracy: 0.7500 - val_loss: 0.4876
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4474 - val_accuracy: 0.7500 - val_loss: 0.4875
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4472 - val_accuracy: 0.7500 - val_loss: 0.4873
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.9167 - loss: 0.4471 - val_accuracy: 0.7500 - val_loss: 0.4871
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4469 - val_accuracy: 0.7500 - val_loss: 0.4869
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4467 - val_accuracy: 0.7500 - val_loss: 0.4868
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4465 - val_accuracy: 0.7500 - val_loss: 0.4866
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4463 - val_accuracy: 0.7500 - val_loss: 0.4864
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4461 - val_accuracy: 0.7500 - val_loss: 0.4863
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4460 - val_accuracy: 0.7500 - val_loss: 0.4861
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4458 - val_accuracy: 0.7500 - val_loss: 0.4859
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4456 - val_accuracy: 0.7500 - val_loss: 0.4857
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4454 - val_accuracy: 0.7500 - val_loss: 0.4856
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4452 - val_accuracy: 0.7500 - val_loss: 0.4854
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9167 - loss: 0.4450 - val_accuracy: 0.7500 - val_loss: 0.4852
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.9167 - loss: 0.4449 - val_accuracy: 0.7500 - val_loss: 0.4851
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9167 - loss: 0.4447 - val_accuracy: 0.7500 - val_loss: 0.4849
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.9167 - loss: 0.4445 - val_accuracy: 0.7500 - val_loss: 0.4847
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.9167 - loss: 0.4443 - val_accuracy: 0.7500 - val_loss: 0.4845
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4441 - val_accuracy: 0.7500 - val_loss: 0.4844
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4439 - val_accuracy: 0.7500 - val_loss: 0.4842
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4438 - val_accuracy: 0.7500 - val_loss: 0.4840
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4436 - val_accuracy: 0.7500 - val_loss: 0.4839
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4434 - val_accuracy: 0.7500 - val_loss: 0.4837
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4432 - val_accuracy: 0.7500 - val_loss: 0.4835
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4430 - val_accuracy: 0.7500 - val_loss: 0.4833
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.9167 - loss: 0.4428 - val_accuracy: 0.7500 - val_loss: 0.4832
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.9167 - loss: 0.4427 - val_accuracy: 0.7500 - val_loss: 0.4830
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4425 - val_accuracy: 0.7500 - val_loss: 0.4828
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9167 - loss: 0.4423 - val_accuracy: 0.7500 - val_loss: 0.4827
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9167 - loss: 0.4421 - val_accuracy: 0.7500 - val_loss: 0.4825
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.9167 - loss: 0.4419 - val_accuracy: 0.7500 - val_loss: 0.4823
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9167 - loss: 0.4417 - val_accuracy: 0.7500 - val_loss: 0.4821
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4416 - val_accuracy: 0.7500 - val_loss: 0.4820
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4414 - val_accuracy: 0.7500 - val_loss: 0.4818
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.9167 - loss: 0.4412 - val_accuracy: 0.7500 - val_loss: 0.4816
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9167 - loss: 0.4410 - val_accuracy: 0.7500 - val_loss: 0.4815
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.9167 - loss: 0.4408 - val_accuracy: 0.7500 - val_loss: 0.4813
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 0.9167 - loss: 0.4406 - val_accuracy: 0.7500 - val_loss: 0.4811
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4405 - val_accuracy: 0.7500 - val_loss: 0.4809
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4403 - val_accuracy: 0.7500 - val_loss: 0.4808
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9167 - loss: 0.4401 - val_accuracy: 0.7500 - val_loss: 0.4806
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4399 - val_accuracy: 0.7500 - val_loss: 0.4804
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9167 - loss: 0.4397 - val_accuracy: 0.7500 - val_loss: 0.4803
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4396 - val_accuracy: 0.7500 - val_loss: 0.4801
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.9167 - loss: 0.4394 - val_accuracy: 0.7500 - val_loss: 0.4799
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4392 - val_accuracy: 0.7500 - val_loss: 0.4798
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9167 - loss: 0.4390 - val_accuracy: 0.7500 - val_loss: 0.4796
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4388 - val_accuracy: 0.7500 - val_loss: 0.4794
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4386 - val_accuracy: 0.7500 - val_loss: 0.4792
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.9167 - loss: 0.4385 - val_accuracy: 0.7500 - val_loss: 0.4791
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.9167 - loss: 0.4383 - val_accuracy: 0.7500 - val_loss: 0.4789
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4381 - val_accuracy: 0.7500 - val_loss: 0.4787
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9167 - loss: 0.4379 - val_accuracy: 0.7500 - val_loss: 0.4786
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4377 - val_accuracy: 0.7500 - val_loss: 0.4784
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.9167 - loss: 0.4376 - val_accuracy: 0.7500 - val_loss: 0.4782
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.9167 - loss: 0.4374 - val_accuracy: 0.7500 - val_loss: 0.4781
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9167 - loss: 0.4372 - val_accuracy: 0.7500 - val_loss: 0.4779
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.4370 - val_accuracy: 0.7500 - val_loss: 0.4777

### Stochastic Gradient Descent

In [44]:
history_Stocahstic = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=1,verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4407 - val_accuracy: 0.7500 - val_loss: 0.4760
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4384 - val_accuracy: 0.7500 - val_loss: 0.4749
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4365 - val_accuracy: 0.7500 - val_loss: 0.4723
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4344 - val_accuracy: 0.7500 - val_loss: 0.4705
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4323 - val_accuracy: 0.7500 - val_loss: 0.4685
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4302 - val_accuracy: 0.7500 - val_loss: 0.4661
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4281 - val_accuracy: 0.7500 - val_loss: 0.4641
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4261 - val_accuracy: 0.7500 - val_loss: 0.4623
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4237 - val_accuracy: 0.7500 - val_loss: 0.4615
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4219 - val_accuracy: 0.7500 - val_loss: 0.4592
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4199 - val_accuracy: 0.7500 - val_loss: 0.4567
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4179 - val_accuracy: 0.7500 - val_loss: 0.4548
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4157 - val_accuracy: 0.7500 - val_loss: 0.4519
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.4138 - val_accuracy: 0.7500 - val_loss: 0.4498
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4115 - val_accuracy: 0.7500 - val_loss: 0.4494
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4098 - val_accuracy: 0.7500 - val_loss: 0.4468
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4078 - val_accuracy: 0.7500 - val_loss: 0.4460
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4060 - val_accuracy: 0.7500 - val_loss: 0.4441
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4040 - val_accuracy: 0.7500 - val_loss: 0.4416
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4018 - val_accuracy: 0.7500 - val_loss: 0.4409
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4002 - val_accuracy: 0.7500 - val_loss: 0.4388
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3981 - val_accuracy: 0.7500 - val_loss: 0.4358
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3960 - val_accuracy: 0.7500 - val_loss: 0.4356
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3943 - val_accuracy: 0.7500 - val_loss: 0.4321
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3924 - val_accuracy: 0.7500 - val_loss: 0.4291
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3908 - val_accuracy: 0.7500 - val_loss: 0.4282
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3880 - val_accuracy: 0.7500 - val_loss: 0.4238
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3871 - val_accuracy: 0.7500 - val_loss: 0.4236
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3852 - val_accuracy: 0.7500 - val_loss: 0.4233
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3835 - val_accuracy: 0.7500 - val_loss: 0.4208
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3811 - val_accuracy: 0.7500 - val_loss: 0.4171
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3801 - val_accuracy: 0.7500 - val_loss: 0.4153
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3781 - val_accuracy: 0.7500 - val_loss: 0.4156
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3766 - val_accuracy: 0.7500 - val_loss: 0.4139
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3749 - val_accuracy: 0.7500 - val_loss: 0.4128
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3731 - val_accuracy: 0.7500 - val_loss: 0.4123
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.3713 - val_accuracy: 0.7500 - val_loss: 0.4098
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3697 - val_accuracy: 0.7500 - val_loss: 0.4084
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3680 - val_accuracy: 0.7500 - val_loss: 0.4061
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3663 - val_accuracy: 0.7500 - val_loss: 0.4057
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3646 - val_accuracy: 0.7500 - val_loss: 0.4039
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3631 - val_accuracy: 0.7500 - val_loss: 0.4027
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3614 - val_accuracy: 0.7500 - val_loss: 0.4008
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3599 - val_accuracy: 0.7500 - val_loss: 0.3993
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3582 - val_accuracy: 0.7500 - val_loss: 0.3984
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3567 - val_accuracy: 0.7500 - val_loss: 0.3969
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3550 - val_accuracy: 0.7500 - val_loss: 0.3941
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3536 - val_accuracy: 0.7500 - val_loss: 0.3931
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3519 - val_accuracy: 0.7500 - val_loss: 0.3913
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3503 - val_accuracy: 0.7500 - val_loss: 0.3893
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3488 - val_accuracy: 0.7500 - val_loss: 0.3895
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3474 - val_accuracy: 0.7500 - val_loss: 0.3882
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3458 - val_accuracy: 0.7500 - val_loss: 0.3876
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3444 - val_accuracy: 0.7500 - val_loss: 0.3867
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3428 - val_accuracy: 0.7500 - val_loss: 0.3836
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.3412 - val_accuracy: 0.7500 - val_loss: 0.3836
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3398 - val_accuracy: 0.7500 - val_loss: 0.3802
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.3385 - val_accuracy: 0.7500 - val_loss: 0.3802
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3371 - val_accuracy: 0.7500 - val_loss: 0.3783
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3356 - val_accuracy: 0.7500 - val_loss: 0.3759
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3339 - val_accuracy: 0.7500 - val_loss: 0.3727
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3330 - val_accuracy: 0.7500 - val_loss: 0.3714
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3310 - val_accuracy: 0.7500 - val_loss: 0.3728
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3302 - val_accuracy: 0.7500 - val_loss: 0.3712
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3283 - val_accuracy: 0.7500 - val_loss: 0.3679
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3274 - val_accuracy: 0.7500 - val_loss: 0.3664
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3261 - val_accuracy: 0.7500 - val_loss: 0.3657
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3247 - val_accuracy: 0.7500 - val_loss: 0.3659
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3232 - val_accuracy: 0.7500 - val_loss: 0.3654
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3221 - val_accuracy: 0.7500 - val_loss: 0.3648
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3208 - val_accuracy: 0.7500 - val_loss: 0.3640
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3195 - val_accuracy: 0.7500 - val_loss: 0.3633
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.3178 - val_accuracy: 0.7500 - val_loss: 0.3597
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3168 - val_accuracy: 0.7500 - val_loss: 0.3594
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3150 - val_accuracy: 0.7500 - val_loss: 0.3555
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3144 - val_accuracy: 0.7500 - val_loss: 0.3544
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.3130 - val_accuracy: 0.7500 - val_loss: 0.3553
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3118 - val_accuracy: 0.7500 - val_loss: 0.3550
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3103 - val_accuracy: 0.7500 - val_loss: 0.3559
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3091 - val_accuracy: 0.7500 - val_loss: 0.3525
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.3082 - val_accuracy: 0.7500 - val_loss: 0.3518
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3068 - val_accuracy: 0.7500 - val_loss: 0.3524
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3053 - val_accuracy: 0.7500 - val_loss: 0.3488
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3046 - val_accuracy: 0.7500 - val_loss: 0.3484
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3024 - val_accuracy: 0.7500 - val_loss: 0.3442
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3022 - val_accuracy: 0.7500 - val_loss: 0.3434
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3011 - val_accuracy: 0.7500 - val_loss: 0.3437
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2995 - val_accuracy: 0.7500 - val_loss: 0.3452
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2983 - val_accuracy: 0.7500 - val_loss: 0.3420
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2976 - val_accuracy: 0.7500 - val_loss: 0.3403
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2964 - val_accuracy: 0.7500 - val_loss: 0.3390
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.2953 - val_accuracy: 0.7500 - val_loss: 0.3396
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2941 - val_accuracy: 0.7500 - val_loss: 0.3389
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2928 - val_accuracy: 0.7500 - val_loss: 0.3365
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2919 - val_accuracy: 0.7500 - val_loss: 0.3354
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2907 - val_accuracy: 0.7500 - val_loss: 0.3363
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.2896 - val_accuracy: 0.7500 - val_loss: 0.3369
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2887 - val_accuracy: 0.7500 - val_loss: 0.3364
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2876 - val_accuracy: 0.7500 - val_loss: 0.3352
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2865 - val_accuracy: 0.7500 - val_loss: 0.3340

### Mini Batch Gradient Descent

In [45]:
history_miniBatch = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=3,verbose=1
)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.2823 - val_accuracy: 0.7500 - val_loss: 0.3335
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2813 - val_accuracy: 0.7500 - val_loss: 0.3333
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2806 - val_accuracy: 0.7500 - val_loss: 0.3330
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2789 - val_accuracy: 0.7500 - val_loss: 0.3326
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2796 - val_accuracy: 0.7500 - val_loss: 0.3322
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2784 - val_accuracy: 0.7500 - val_loss: 0.3317
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2780 - val_accuracy: 0.7500 - val_loss: 0.3314
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2782 - val_accuracy: 0.7500 - val_loss: 0.3304
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2783 - val_accuracy: 0.7500 - val_loss: 0.3300
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2767 - val_accuracy: 0.7500 - val_loss: 0.3296
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2778 - val_accuracy: 0.7500 - val_loss: 0.3293
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2769 - val_accuracy: 0.7500 - val_loss: 0.3289
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2770 - val_accuracy: 0.7500 - val_loss: 0.3285
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2767 - val_accuracy: 0.7500 - val_loss: 0.3284
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2753 - val_accuracy: 0.7500 - val_loss: 0.3281
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.2758 - val_accuracy: 0.7500 - val_loss: 0.3279
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2754 - val_accuracy: 0.7500 - val_loss: 0.3273
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2737 - val_accuracy: 0.7500 - val_loss: 0.3270
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2744 - val_accuracy: 0.7500 - val_loss: 0.3269
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2728 - val_accuracy: 0.7500 - val_loss: 0.3266
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2735 - val_accuracy: 0.7500 - val_loss: 0.3264
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2750 - val_accuracy: 0.7500 - val_loss: 0.3263
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.2734 - val_accuracy: 0.7500 - val_loss: 0.3261
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2729 - val_accuracy: 0.7500 - val_loss: 0.3258
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2710 - val_accuracy: 0.7500 - val_loss: 0.3255
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2707 - val_accuracy: 0.7500 - val_loss: 0.3252
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2732 - val_accuracy: 0.7500 - val_loss: 0.3251
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2722 - val_accuracy: 0.7500 - val_loss: 0.3248
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2719 - val_accuracy: 0.7500 - val_loss: 0.3241
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.2703 - val_accuracy: 0.7500 - val_loss: 0.3232
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2704 - val_accuracy: 0.7500 - val_loss: 0.3227
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.2695 - val_accuracy: 0.7500 - val_loss: 0.3224
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2690 - val_accuracy: 0.7500 - val_loss: 0.3217
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.2690 - val_accuracy: 0.7500 - val_loss: 0.3215
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.2695 - val_accuracy: 0.7500 - val_loss: 0.3216
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2674 - val_accuracy: 0.7500 - val_loss: 0.3213
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2710 - val_accuracy: 0.7500 - val_loss: 0.3214
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2688 - val_accuracy: 0.7500 - val_loss: 0.3207
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2678 - val_accuracy: 0.7500 - val_loss: 0.3199
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2668 - val_accuracy: 0.7500 - val_loss: 0.3199
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2689 - val_accuracy: 0.7500 - val_loss: 0.3197
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2680 - val_accuracy: 0.7500 - val_loss: 0.3193
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2657 - val_accuracy: 0.7500 - val_loss: 0.3191
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2657 - val_accuracy: 0.7500 - val_loss: 0.3190
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.2658 - val_accuracy: 0.7500 - val_loss: 0.3187
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2652 - val_accuracy: 0.7500 - val_loss: 0.3184
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.2657 - val_accuracy: 0.7500 - val_loss: 0.3181
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2646 - val_accuracy: 0.7500 - val_loss: 0.3180
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2659 - val_accuracy: 0.7500 - val_loss: 0.3179
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2652 - val_accuracy: 0.7500 - val_loss: 0.3180
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2628 - val_accuracy: 0.7500 - val_loss: 0.3178
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2623 - val_accuracy: 0.7500 - val_loss: 0.3174
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2637 - val_accuracy: 0.7500 - val_loss: 0.3169
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2619 - val_accuracy: 0.7500 - val_loss: 0.3166
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.2634 - val_accuracy: 0.7500 - val_loss: 0.3158
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2627 - val_accuracy: 0.7500 - val_loss: 0.3154
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2613 - val_accuracy: 0.7500 - val_loss: 0.3151
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2625 - val_accuracy: 0.7500 - val_loss: 0.3151
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2607 - val_accuracy: 0.7500 - val_loss: 0.3147
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2609 - val_accuracy: 0.7500 - val_loss: 0.3148
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2611 - val_accuracy: 0.7500 - val_loss: 0.3147
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2599 - val_accuracy: 0.7500 - val_loss: 0.3140
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2593 - val_accuracy: 0.7500 - val_loss: 0.3138
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2612 - val_accuracy: 0.7500 - val_loss: 0.3137
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2593 - val_accuracy: 0.7500 - val_loss: 0.3136
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.2608 - val_accuracy: 0.7500 - val_loss: 0.3127
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2573 - val_accuracy: 0.7500 - val_loss: 0.3125
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2589 - val_accuracy: 0.7500 - val_loss: 0.3124
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2595 - val_accuracy: 0.7500 - val_loss: 0.3115
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2583 - val_accuracy: 0.7500 - val_loss: 0.3117
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.2603 - val_accuracy: 0.7500 - val_loss: 0.3117
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.2577 - val_accuracy: 0.7500 - val_loss: 0.3116
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2570 - val_accuracy: 0.7500 - val_loss: 0.3115
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2569 - val_accuracy: 0.7500 - val_loss: 0.3111
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2576 - val_accuracy: 0.7500 - val_loss: 0.3110
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2552 - val_accuracy: 0.7500 - val_loss: 0.3108
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2559 - val_accuracy: 0.7500 - val_loss: 0.3100
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2559 - val_accuracy: 0.7500 - val_loss: 0.3100
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.2548 - val_accuracy: 0.7500 - val_loss: 0.3092
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2545 - val_accuracy: 0.7500 - val_loss: 0.3090
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2540 - val_accuracy: 0.7500 - val_loss: 0.3082
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2538 - val_accuracy: 0.7500 - val_loss: 0.3082
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.2536 - val_accuracy: 0.7500 - val_loss: 0.3082
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2528 - val_accuracy: 0.7500 - val_loss: 0.3081
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2540 - val_accuracy: 0.7500 - val_loss: 0.3079
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2534 - val_accuracy: 0.7500 - val_loss: 0.3071
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2541 - val_accuracy: 0.7500 - val_loss: 0.3068
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2522 - val_accuracy: 0.7500 - val_loss: 0.3065
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2522 - val_accuracy: 0.7500 - val_loss: 0.3065
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2543 - val_accuracy: 0.7500 - val_loss: 0.3062
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2534 - val_accuracy: 0.7500 - val_loss: 0.3059
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2530 - val_accuracy: 0.7500 - val_loss: 0.3060
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2524 - val_accuracy: 0.7500 - val_loss: 0.3056
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2503 - val_accuracy: 0.7500 - val_loss: 0.3055
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2517 - val_accuracy: 0.7500 - val_loss: 0.3056
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2515 - val_accuracy: 0.7500 - val_loss: 0.3047
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2505 - val_accuracy: 0.7500 - val_loss: 0.3046
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2498 - val_accuracy: 0.7500 - val_loss: 0.3042
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2505 - val_accuracy: 0.7500 - val_loss: 0.3042
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2476 - val_accuracy: 0.7500 - val_loss: 0.3039

In [39]:
from tensorflow.keras import optimizers

In [40]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)