In [47]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\nabee\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (7.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.0.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\nabee\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\nabee\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\nabee\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\nabee\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [48]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [49]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [50]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [51]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [52]:
X= df[['soil_moisture','temperature_c', 'sunlight_hours']]
Y = df['needs_water']

In [53]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/( X_max- X_min + 1e-8)

In [54]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, test_size=0.25, random_state=42)

In [56]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [57]:
from tensorflow.keras import optimizers
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)

In [58]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [59]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=2,verbose=1
)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.5833 - loss: 0.7051 - val_accuracy: 0.2500 - val_loss: 0.8813
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6987 - val_accuracy: 0.2500 - val_loss: 0.8658
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6949 - val_accuracy: 0.2500 - val_loss: 0.8533
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6912 - val_accuracy: 0.2500 - val_loss: 0.8418
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6878 - val_accuracy: 0.2500 - val_loss: 0.8311
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6845 - val_accuracy: 0.2500 - val_loss: 0.8212
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6816 - val_accuracy: 0.2500 - val_loss: 0.8123
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6808 - val_accuracy: 0.2500 - val_loss: 0.8047
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6757 - val_accuracy: 0.5000 - val_loss: 0.7977
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6735 - val_accuracy: 0.5000 - val_loss: 0.7901
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6729 - val_accuracy: 0.5000 - val_loss: 0.7828
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6707 - val_accuracy: 0.5000 - val_loss: 0.7757
Epoch 13/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6684 - val_accuracy: 0.5000 - val_loss: 0.7706
Epoch 14/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6673 - val_accuracy: 0.5000 - val_loss: 0.7658
Epoch 15/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6642 - val_accuracy: 0.5000 - val_loss: 0.7616
Epoch 16/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6630 - val_accuracy: 0.5000 - val_loss: 0.7577
Epoch 17/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6629 - val_accuracy: 0.5000 - val_loss: 0.7538
Epoch 18/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6611 - val_accuracy: 0.5000 - val_loss: 0.7504
Epoch 19/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6598 - val_accuracy: 0.5000 - val_loss: 0.7469
Epoch 20/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.6609 - val_accuracy: 0.5000 - val_loss: 0.7432
Epoch 21/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6595 - val_accuracy: 0.5000 - val_loss: 0.7403
Epoch 22/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6577 - val_accuracy: 0.5000 - val_loss: 0.7376
Epoch 23/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6571 - val_accuracy: 0.5000 - val_loss: 0.7346
Epoch 24/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6548 - val_accuracy: 0.5000 - val_loss: 0.7322
Epoch 25/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6547 - val_accuracy: 0.5000 - val_loss: 0.7297
Epoch 26/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6509 - val_accuracy: 0.5000 - val_loss: 0.7274
Epoch 27/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6509 - val_accuracy: 0.5000 - val_loss: 0.7247
Epoch 28/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.6499 - val_accuracy: 0.5000 - val_loss: 0.7225
Epoch 29/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6469 - val_accuracy: 0.5000 - val_loss: 0.7202
Epoch 30/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6473 - val_accuracy: 0.5000 - val_loss: 0.7180
Epoch 31/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6450 - val_accuracy: 0.5000 - val_loss: 0.7161
Epoch 32/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6456 - val_accuracy: 0.5000 - val_loss: 0.7141
Epoch 33/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6431 - val_accuracy: 0.5000 - val_loss: 0.7124
Epoch 34/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6439 - val_accuracy: 0.5000 - val_loss: 0.7107
Epoch 35/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6408 - val_accuracy: 0.5000 - val_loss: 0.7089
Epoch 36/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6410 - val_accuracy: 0.5000 - val_loss: 0.7072
Epoch 37/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6404 - val_accuracy: 0.5000 - val_loss: 0.7057
Epoch 38/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6377 - val_accuracy: 0.5000 - val_loss: 0.7040
Epoch 39/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6377 - val_accuracy: 0.5000 - val_loss: 0.7022
Epoch 40/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6370 - val_accuracy: 0.5000 - val_loss: 0.7006
Epoch 41/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6357 - val_accuracy: 0.5000 - val_loss: 0.6992
Epoch 42/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6347 - val_accuracy: 0.5000 - val_loss: 0.6977
Epoch 43/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6336 - val_accuracy: 0.5000 - val_loss: 0.6961
Epoch 44/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6327 - val_accuracy: 0.5000 - val_loss: 0.6947
Epoch 45/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6320 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 46/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6309 - val_accuracy: 0.5000 - val_loss: 0.6916
Epoch 47/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6296 - val_accuracy: 0.5000 - val_loss: 0.6903
Epoch 48/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6285 - val_accuracy: 0.5000 - val_loss: 0.6891
Epoch 49/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6278 - val_accuracy: 0.5000 - val_loss: 0.6873
Epoch 50/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6266 - val_accuracy: 0.5000 - val_loss: 0.6857
Epoch 51/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6254 - val_accuracy: 0.5000 - val_loss: 0.6842
Epoch 52/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6239 - val_accuracy: 0.5000 - val_loss: 0.6828
Epoch 53/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6217 - val_accuracy: 0.5000 - val_loss: 0.6814
Epoch 54/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6226 - val_accuracy: 0.5000 - val_loss: 0.6800
Epoch 55/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6207 - val_accuracy: 0.5000 - val_loss: 0.6789
Epoch 56/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6196 - val_accuracy: 0.5000 - val_loss: 0.6775
Epoch 57/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6186 - val_accuracy: 0.5000 - val_loss: 0.6762
Epoch 58/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6171 - val_accuracy: 0.5000 - val_loss: 0.6749
Epoch 59/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6168 - val_accuracy: 0.5000 - val_loss: 0.6736
Epoch 60/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6138 - val_accuracy: 0.5000 - val_loss: 0.6724
Epoch 61/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6140 - val_accuracy: 0.5000 - val_loss: 0.6713
Epoch 62/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6128 - val_accuracy: 0.5000 - val_loss: 0.6701
Epoch 63/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6098 - val_accuracy: 0.5000 - val_loss: 0.6687
Epoch 64/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6104 - val_accuracy: 0.5000 - val_loss: 0.6675
Epoch 65/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6097 - val_accuracy: 0.5000 - val_loss: 0.6661
Epoch 66/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6076 - val_accuracy: 0.5000 - val_loss: 0.6646
Epoch 67/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6070 - val_accuracy: 0.5000 - val_loss: 0.6631
Epoch 68/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6043 - val_accuracy: 0.2500 - val_loss: 0.6620
Epoch 69/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6045 - val_accuracy: 0.2500 - val_loss: 0.6606
Epoch 70/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6034 - val_accuracy: 0.2500 - val_loss: 0.6592
Epoch 71/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6016 - val_accuracy: 0.2500 - val_loss: 0.6582
Epoch 72/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5992 - val_accuracy: 0.2500 - val_loss: 0.6568
Epoch 73/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5992 - val_accuracy: 0.2500 - val_loss: 0.6556
Epoch 74/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5985 - val_accuracy: 0.2500 - val_loss: 0.6540
Epoch 75/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5955 - val_accuracy: 0.2500 - val_loss: 0.6528
Epoch 76/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.5958 - val_accuracy: 0.2500 - val_loss: 0.6515
Epoch 77/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5943 - val_accuracy: 0.2500 - val_loss: 0.6502
Epoch 78/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5936 - val_accuracy: 0.2500 - val_loss: 0.6488
Epoch 79/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5919 - val_accuracy: 0.2500 - val_loss: 0.6475
Epoch 80/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5910 - val_accuracy: 0.2500 - val_loss: 0.6458
Epoch 81/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.5895 - val_accuracy: 0.2500 - val_loss: 0.6448
Epoch 82/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5870 - val_accuracy: 0.2500 - val_loss: 0.6436
Epoch 83/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5870 - val_accuracy: 0.2500 - val_loss: 0.6421
Epoch 84/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5858 - val_accuracy: 0.2500 - val_loss: 0.6408
Epoch 85/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5849 - val_accuracy: 0.2500 - val_loss: 0.6396
Epoch 86/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5833 - val_accuracy: 0.2500 - val_loss: 0.6381
Epoch 87/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5812 - val_accuracy: 0.2500 - val_loss: 0.6365
Epoch 88/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5807 - val_accuracy: 0.2500 - val_loss: 0.6353
Epoch 89/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7500 - loss: 0.5777 - val_accuracy: 0.2500 - val_loss: 0.6341
Epoch 90/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5778 - val_accuracy: 0.2500 - val_loss: 0.6326
Epoch 91/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5782 - val_accuracy: 0.2500 - val_loss: 0.6310
Epoch 92/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5756 - val_accuracy: 0.5000 - val_loss: 0.6297
Epoch 93/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.5743 - val_accuracy: 0.5000 - val_loss: 0.6283
Epoch 94/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5735 - val_accuracy: 0.7500 - val_loss: 0.6273
Epoch 95/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5720 - val_accuracy: 0.7500 - val_loss: 0.6261
Epoch 96/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7500 - loss: 0.5714 - val_accuracy: 0.7500 - val_loss: 0.6248
Epoch 97/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5682 - val_accuracy: 0.7500 - val_loss: 0.6234
Epoch 98/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5687 - val_accuracy: 0.7500 - val_loss: 0.6224
Epoch 99/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5670 - val_accuracy: 0.7500 - val_loss: 0.6209
Epoch 100/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.5665 - val_accuracy: 0.7500 - val_loss: 0.6194

### Full Batch Gradient Descent

In [60]:
history_full_batch = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=len(X_train),verbose=1
)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 445ms/step - accuracy: 0.7500 - loss: 0.5628 - val_accuracy: 0.7500 - val_loss: 0.6192
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.5626 - val_accuracy: 0.7500 - val_loss: 0.6189
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.5624 - val_accuracy: 0.7500 - val_loss: 0.6187
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5622 - val_accuracy: 0.7500 - val_loss: 0.6185
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.5620 - val_accuracy: 0.7500 - val_loss: 0.6182
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7500 - loss: 0.5618 - val_accuracy: 0.7500 - val_loss: 0.6180
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.7500 - loss: 0.5616 - val_accuracy: 0.7500 - val_loss: 0.6178
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5614 - val_accuracy: 0.7500 - val_loss: 0.6175
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5612 - val_accuracy: 0.7500 - val_loss: 0.6173
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5610 - val_accuracy: 0.7500 - val_loss: 0.6171
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5608 - val_accuracy: 0.7500 - val_loss: 0.6168
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.5606 - val_accuracy: 0.7500 - val_loss: 0.6166
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5604 - val_accuracy: 0.7500 - val_loss: 0.6163
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.7500 - loss: 0.5601 - val_accuracy: 0.7500 - val_loss: 0.6161
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5599 - val_accuracy: 0.7500 - val_loss: 0.6159
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7500 - loss: 0.5597 - val_accuracy: 0.7500 - val_loss: 0.6156
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.5595 - val_accuracy: 0.7500 - val_loss: 0.6154
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5593 - val_accuracy: 0.7500 - val_loss: 0.6151
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5591 - val_accuracy: 0.7500 - val_loss: 0.6149
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.7500 - loss: 0.5589 - val_accuracy: 0.7500 - val_loss: 0.6147
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5587 - val_accuracy: 0.7500 - val_loss: 0.6144
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5585 - val_accuracy: 0.7500 - val_loss: 0.6142
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5583 - val_accuracy: 0.7500 - val_loss: 0.6139
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5581 - val_accuracy: 0.7500 - val_loss: 0.6137
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5579 - val_accuracy: 0.7500 - val_loss: 0.6135
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5577 - val_accuracy: 0.7500 - val_loss: 0.6132
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.5574 - val_accuracy: 0.7500 - val_loss: 0.6130
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5572 - val_accuracy: 0.7500 - val_loss: 0.6127
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5570 - val_accuracy: 0.7500 - val_loss: 0.6125
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5568 - val_accuracy: 0.7500 - val_loss: 0.6123
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5566 - val_accuracy: 0.7500 - val_loss: 0.6120
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.5564 - val_accuracy: 0.7500 - val_loss: 0.6118
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.7500 - loss: 0.5562 - val_accuracy: 0.7500 - val_loss: 0.6115
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5560 - val_accuracy: 0.7500 - val_loss: 0.6113
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7500 - loss: 0.5558 - val_accuracy: 0.7500 - val_loss: 0.6110
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5556 - val_accuracy: 0.7500 - val_loss: 0.6108
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5554 - val_accuracy: 0.7500 - val_loss: 0.6105
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.5551 - val_accuracy: 0.7500 - val_loss: 0.6103
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5549 - val_accuracy: 0.7500 - val_loss: 0.6101
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.7500 - loss: 0.5547 - val_accuracy: 0.7500 - val_loss: 0.6098
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5545 - val_accuracy: 0.7500 - val_loss: 0.6096
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5543 - val_accuracy: 0.7500 - val_loss: 0.6093
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5541 - val_accuracy: 0.7500 - val_loss: 0.6091
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5539 - val_accuracy: 0.7500 - val_loss: 0.6088
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.5537 - val_accuracy: 0.7500 - val_loss: 0.6086
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5535 - val_accuracy: 0.7500 - val_loss: 0.6083
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5532 - val_accuracy: 0.7500 - val_loss: 0.6081
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5530 - val_accuracy: 0.7500 - val_loss: 0.6078
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5528 - val_accuracy: 0.7500 - val_loss: 0.6076
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.5526 - val_accuracy: 0.7500 - val_loss: 0.6073
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5524 - val_accuracy: 0.7500 - val_loss: 0.6071
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5522 - val_accuracy: 0.7500 - val_loss: 0.6069
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5520 - val_accuracy: 0.7500 - val_loss: 0.6066
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7500 - loss: 0.5518 - val_accuracy: 0.7500 - val_loss: 0.6064
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.7500 - loss: 0.5515 - val_accuracy: 0.7500 - val_loss: 0.6061
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.7500 - loss: 0.5513 - val_accuracy: 0.7500 - val_loss: 0.6059
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7500 - loss: 0.5511 - val_accuracy: 0.7500 - val_loss: 0.6056
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5509 - val_accuracy: 0.7500 - val_loss: 0.6054
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5507 - val_accuracy: 0.7500 - val_loss: 0.6051
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5505 - val_accuracy: 0.7500 - val_loss: 0.6049
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.7500 - loss: 0.5503 - val_accuracy: 0.7500 - val_loss: 0.6046
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.7500 - loss: 0.5501 - val_accuracy: 0.7500 - val_loss: 0.6044
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.7500 - loss: 0.5498 - val_accuracy: 0.7500 - val_loss: 0.6041
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5496 - val_accuracy: 0.7500 - val_loss: 0.6039
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7500 - loss: 0.5494 - val_accuracy: 0.7500 - val_loss: 0.6036
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.7500 - loss: 0.5492 - val_accuracy: 0.7500 - val_loss: 0.6034
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.5490 - val_accuracy: 0.7500 - val_loss: 0.6031
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.7500 - loss: 0.5488 - val_accuracy: 0.7500 - val_loss: 0.6029
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5486 - val_accuracy: 0.7500 - val_loss: 0.6026
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7500 - loss: 0.5484 - val_accuracy: 0.7500 - val_loss: 0.6024
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.7500 - loss: 0.5481 - val_accuracy: 0.7500 - val_loss: 0.6021
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.7500 - loss: 0.5479 - val_accuracy: 0.7500 - val_loss: 0.6019
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7500 - loss: 0.5477 - val_accuracy: 0.7500 - val_loss: 0.6016
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.7500 - loss: 0.5475 - val_accuracy: 0.7500 - val_loss: 0.6014
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.7500 - loss: 0.5473 - val_accuracy: 0.7500 - val_loss: 0.6011
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7500 - loss: 0.5471 - val_accuracy: 0.7500 - val_loss: 0.6009
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.7500 - loss: 0.5469 - val_accuracy: 0.7500 - val_loss: 0.6006
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5466 - val_accuracy: 0.7500 - val_loss: 0.6003
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.7500 - loss: 0.5464 - val_accuracy: 0.7500 - val_loss: 0.6001
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7500 - loss: 0.5462 - val_accuracy: 0.7500 - val_loss: 0.5998
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5460 - val_accuracy: 0.7500 - val_loss: 0.5996
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5458 - val_accuracy: 0.7500 - val_loss: 0.5993
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8333 - loss: 0.5456 - val_accuracy: 0.7500 - val_loss: 0.5991
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8333 - loss: 0.5453 - val_accuracy: 0.7500 - val_loss: 0.5988
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.8333 - loss: 0.5451 - val_accuracy: 0.7500 - val_loss: 0.5986
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.8333 - loss: 0.5449 - val_accuracy: 0.7500 - val_loss: 0.5983
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.8333 - loss: 0.5447 - val_accuracy: 0.7500 - val_loss: 0.5981
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.8333 - loss: 0.5445 - val_accuracy: 0.7500 - val_loss: 0.5978
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.8333 - loss: 0.5443 - val_accuracy: 0.7500 - val_loss: 0.5976
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.8333 - loss: 0.5440 - val_accuracy: 0.7500 - val_loss: 0.5973
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8333 - loss: 0.5438 - val_accuracy: 0.7500 - val_loss: 0.5970
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.8333 - loss: 0.5436 - val_accuracy: 0.7500 - val_loss: 0.5968
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.8333 - loss: 0.5434 - val_accuracy: 0.7500 - val_loss: 0.5965
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.8333 - loss: 0.5432 - val_accuracy: 0.7500 - val_loss: 0.5963
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.8333 - loss: 0.5430 - val_accuracy: 0.7500 - val_loss: 0.5960
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8333 - loss: 0.5428 - val_accuracy: 0.7500 - val_loss: 0.5958
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8333 - loss: 0.5425 - val_accuracy: 0.7500 - val_loss: 0.5955
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.8333 - loss: 0.5423 - val_accuracy: 0.7500 - val_loss: 0.5953
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8333 - loss: 0.5421 - val_accuracy: 0.7500 - val_loss: 0.5950
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8333 - loss: 0.5419 - val_accuracy: 0.7500 - val_loss: 0.5947

### Stochastic Gradient Descent

In [61]:
history_Stocahstic = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=1,verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8333 - loss: 0.5457 - val_accuracy: 0.7500 - val_loss: 0.5906
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5431 - val_accuracy: 0.7500 - val_loss: 0.5864
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5404 - val_accuracy: 0.7500 - val_loss: 0.5819
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5381 - val_accuracy: 0.7500 - val_loss: 0.5792
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5354 - val_accuracy: 0.7500 - val_loss: 0.5776
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5328 - val_accuracy: 0.7500 - val_loss: 0.5731
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5303 - val_accuracy: 0.7500 - val_loss: 0.5712
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5279 - val_accuracy: 0.7500 - val_loss: 0.5678
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5252 - val_accuracy: 0.7500 - val_loss: 0.5635
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5226 - val_accuracy: 0.7500 - val_loss: 0.5616
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5201 - val_accuracy: 0.7500 - val_loss: 0.5581
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5175 - val_accuracy: 0.7500 - val_loss: 0.5546
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8333 - loss: 0.5147 - val_accuracy: 0.7500 - val_loss: 0.5502
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5120 - val_accuracy: 0.7500 - val_loss: 0.5485
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5096 - val_accuracy: 0.7500 - val_loss: 0.5447
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5070 - val_accuracy: 0.7500 - val_loss: 0.5411
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5043 - val_accuracy: 0.7500 - val_loss: 0.5371
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5019 - val_accuracy: 0.7500 - val_loss: 0.5340
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4990 - val_accuracy: 0.7500 - val_loss: 0.5323
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4965 - val_accuracy: 0.7500 - val_loss: 0.5285
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4939 - val_accuracy: 0.7500 - val_loss: 0.5248
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4914 - val_accuracy: 0.7500 - val_loss: 0.5230
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4886 - val_accuracy: 0.7500 - val_loss: 0.5184
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4863 - val_accuracy: 0.7500 - val_loss: 0.5151
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4836 - val_accuracy: 0.7500 - val_loss: 0.5136
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4809 - val_accuracy: 0.7500 - val_loss: 0.5123
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4786 - val_accuracy: 0.7500 - val_loss: 0.5087
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4759 - val_accuracy: 0.7500 - val_loss: 0.5062
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4734 - val_accuracy: 0.7500 - val_loss: 0.5032
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4707 - val_accuracy: 0.7500 - val_loss: 0.4986
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4682 - val_accuracy: 0.7500 - val_loss: 0.4952
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4656 - val_accuracy: 0.7500 - val_loss: 0.4910
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4631 - val_accuracy: 0.7500 - val_loss: 0.4879
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4606 - val_accuracy: 0.7500 - val_loss: 0.4842
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4582 - val_accuracy: 0.7500 - val_loss: 0.4820
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4555 - val_accuracy: 0.7500 - val_loss: 0.4803
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4530 - val_accuracy: 0.7500 - val_loss: 0.4770
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4505 - val_accuracy: 0.7500 - val_loss: 0.4733
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4480 - val_accuracy: 0.7500 - val_loss: 0.4717
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4455 - val_accuracy: 0.7500 - val_loss: 0.4684
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.4431 - val_accuracy: 0.7500 - val_loss: 0.4646
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4405 - val_accuracy: 0.7500 - val_loss: 0.4631
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4383 - val_accuracy: 0.7500 - val_loss: 0.4602
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4357 - val_accuracy: 0.7500 - val_loss: 0.4578
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4334 - val_accuracy: 0.7500 - val_loss: 0.4556
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4309 - val_accuracy: 0.7500 - val_loss: 0.4522
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4284 - val_accuracy: 0.7500 - val_loss: 0.4506
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.4263 - val_accuracy: 0.7500 - val_loss: 0.4472
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4233 - val_accuracy: 0.7500 - val_loss: 0.4463
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4215 - val_accuracy: 0.7500 - val_loss: 0.4439
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4188 - val_accuracy: 0.7500 - val_loss: 0.4427
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4170 - val_accuracy: 0.7500 - val_loss: 0.4393
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4147 - val_accuracy: 0.7500 - val_loss: 0.4360
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4123 - val_accuracy: 0.7500 - val_loss: 0.4325
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4096 - val_accuracy: 0.7500 - val_loss: 0.4315
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4077 - val_accuracy: 0.7500 - val_loss: 0.4284
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4056 - val_accuracy: 0.7500 - val_loss: 0.4246
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4034 - val_accuracy: 0.7500 - val_loss: 0.4221
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4008 - val_accuracy: 0.7500 - val_loss: 0.4178
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3990 - val_accuracy: 0.7500 - val_loss: 0.4149
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3967 - val_accuracy: 0.7500 - val_loss: 0.4134
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3946 - val_accuracy: 0.7500 - val_loss: 0.4118
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3918 - val_accuracy: 0.7500 - val_loss: 0.4068
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3904 - val_accuracy: 0.7500 - val_loss: 0.4055
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.3884 - val_accuracy: 0.7500 - val_loss: 0.4027
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3861 - val_accuracy: 0.7500 - val_loss: 0.4022
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3843 - val_accuracy: 0.7500 - val_loss: 0.3998
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3821 - val_accuracy: 0.7500 - val_loss: 0.3989
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3799 - val_accuracy: 0.7500 - val_loss: 0.3983
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3782 - val_accuracy: 0.7500 - val_loss: 0.3951
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3763 - val_accuracy: 0.7500 - val_loss: 0.3930
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3744 - val_accuracy: 0.7500 - val_loss: 0.3911
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3724 - val_accuracy: 0.7500 - val_loss: 0.3876
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3704 - val_accuracy: 0.7500 - val_loss: 0.3857
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3684 - val_accuracy: 0.7500 - val_loss: 0.3822
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3667 - val_accuracy: 0.7500 - val_loss: 0.3803
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3648 - val_accuracy: 0.7500 - val_loss: 0.3789
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3625 - val_accuracy: 0.7500 - val_loss: 0.3750
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3609 - val_accuracy: 0.7500 - val_loss: 0.3721
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3589 - val_accuracy: 0.7500 - val_loss: 0.3729
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3568 - val_accuracy: 0.7500 - val_loss: 0.3736
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3556 - val_accuracy: 0.7500 - val_loss: 0.3702
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3536 - val_accuracy: 0.7500 - val_loss: 0.3700
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3522 - val_accuracy: 0.7500 - val_loss: 0.3684
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3502 - val_accuracy: 0.7500 - val_loss: 0.3676
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.3487 - val_accuracy: 0.7500 - val_loss: 0.3642
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3469 - val_accuracy: 0.7500 - val_loss: 0.3628
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3446 - val_accuracy: 0.7500 - val_loss: 0.3579
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3435 - val_accuracy: 0.7500 - val_loss: 0.3558
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3418 - val_accuracy: 0.7500 - val_loss: 0.3530
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3402 - val_accuracy: 0.7500 - val_loss: 0.3522
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3386 - val_accuracy: 0.7500 - val_loss: 0.3497
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3366 - val_accuracy: 0.7500 - val_loss: 0.3506
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3352 - val_accuracy: 0.7500 - val_loss: 0.3481
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3337 - val_accuracy: 0.7500 - val_loss: 0.3464
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3318 - val_accuracy: 0.7500 - val_loss: 0.3432
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3304 - val_accuracy: 0.7500 - val_loss: 0.3417
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3287 - val_accuracy: 0.7500 - val_loss: 0.3390
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3275 - val_accuracy: 0.7500 - val_loss: 0.3382
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3259 - val_accuracy: 0.7500 - val_loss: 0.3383

### Mini Batch Gradient Descent

In [62]:
history_miniBatch = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=3,verbose=1
)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.3202 - val_accuracy: 0.7500 - val_loss: 0.3380
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3186 - val_accuracy: 0.7500 - val_loss: 0.3375
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.3213 - val_accuracy: 0.7500 - val_loss: 0.3374
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3184 - val_accuracy: 0.7500 - val_loss: 0.3367
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3205 - val_accuracy: 0.7500 - val_loss: 0.3363
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3188 - val_accuracy: 0.7500 - val_loss: 0.3355
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3184 - val_accuracy: 0.7500 - val_loss: 0.3353
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3152 - val_accuracy: 0.7500 - val_loss: 0.3348
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3173 - val_accuracy: 0.7500 - val_loss: 0.3346
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3146 - val_accuracy: 0.7500 - val_loss: 0.3342
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3140 - val_accuracy: 0.7500 - val_loss: 0.3338
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3156 - val_accuracy: 0.7500 - val_loss: 0.3333
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3151 - val_accuracy: 0.7500 - val_loss: 0.3328
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3119 - val_accuracy: 0.7500 - val_loss: 0.3322
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3127 - val_accuracy: 0.7500 - val_loss: 0.3317
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.3140 - val_accuracy: 0.7500 - val_loss: 0.3309
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3128 - val_accuracy: 0.7500 - val_loss: 0.3302
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.3117 - val_accuracy: 0.7500 - val_loss: 0.3298
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3094 - val_accuracy: 0.7500 - val_loss: 0.3293
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.3108 - val_accuracy: 0.7500 - val_loss: 0.3291
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3089 - val_accuracy: 0.7500 - val_loss: 0.3285
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3100 - val_accuracy: 0.7500 - val_loss: 0.3278
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3073 - val_accuracy: 0.7500 - val_loss: 0.3273
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3100 - val_accuracy: 0.7500 - val_loss: 0.3266
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3078 - val_accuracy: 0.7500 - val_loss: 0.3265
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3094 - val_accuracy: 0.7500 - val_loss: 0.3262
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3078 - val_accuracy: 0.7500 - val_loss: 0.3256
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3050 - val_accuracy: 0.7500 - val_loss: 0.3250
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.3067 - val_accuracy: 0.7500 - val_loss: 0.3249
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.3041 - val_accuracy: 0.7500 - val_loss: 0.3250
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3068 - val_accuracy: 0.7500 - val_loss: 0.3247
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3047 - val_accuracy: 0.7500 - val_loss: 0.3242
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3033 - val_accuracy: 0.7500 - val_loss: 0.3238
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.3036 - val_accuracy: 0.7500 - val_loss: 0.3232
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3025 - val_accuracy: 0.7500 - val_loss: 0.3228
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3017 - val_accuracy: 0.7500 - val_loss: 0.3222
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3016 - val_accuracy: 0.7500 - val_loss: 0.3216
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3016 - val_accuracy: 0.7500 - val_loss: 0.3219
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.3002 - val_accuracy: 0.7500 - val_loss: 0.3214
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2994 - val_accuracy: 0.7500 - val_loss: 0.3208
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3016 - val_accuracy: 0.7500 - val_loss: 0.3210
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2993 - val_accuracy: 0.7500 - val_loss: 0.3205
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3002 - val_accuracy: 0.7500 - val_loss: 0.3201
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2986 - val_accuracy: 0.7500 - val_loss: 0.3204
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2979 - val_accuracy: 0.7500 - val_loss: 0.3196
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.3005 - val_accuracy: 0.7500 - val_loss: 0.3189
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2980 - val_accuracy: 0.7500 - val_loss: 0.3184
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.2990 - val_accuracy: 0.7500 - val_loss: 0.3178
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2961 - val_accuracy: 0.7500 - val_loss: 0.3171
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2948 - val_accuracy: 0.7500 - val_loss: 0.3172
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2964 - val_accuracy: 0.7500 - val_loss: 0.3175
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2952 - val_accuracy: 0.7500 - val_loss: 0.3167
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.2946 - val_accuracy: 0.7500 - val_loss: 0.3161
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2965 - val_accuracy: 0.7500 - val_loss: 0.3153
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2944 - val_accuracy: 0.7500 - val_loss: 0.3147
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2945 - val_accuracy: 0.7500 - val_loss: 0.3151
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2940 - val_accuracy: 0.7500 - val_loss: 0.3144
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2916 - val_accuracy: 0.7500 - val_loss: 0.3146
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2912 - val_accuracy: 0.7500 - val_loss: 0.3140
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2908 - val_accuracy: 0.7500 - val_loss: 0.3141
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2918 - val_accuracy: 0.7500 - val_loss: 0.3133
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2906 - val_accuracy: 0.7500 - val_loss: 0.3127
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2901 - val_accuracy: 0.7500 - val_loss: 0.3129
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2920 - val_accuracy: 0.7500 - val_loss: 0.3133
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2897 - val_accuracy: 0.7500 - val_loss: 0.3125
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.2886 - val_accuracy: 0.7500 - val_loss: 0.3126
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2898 - val_accuracy: 0.7500 - val_loss: 0.3125
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2888 - val_accuracy: 0.7500 - val_loss: 0.3120
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2879 - val_accuracy: 0.7500 - val_loss: 0.3121
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2869 - val_accuracy: 0.7500 - val_loss: 0.3115
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2871 - val_accuracy: 0.7500 - val_loss: 0.3107
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2873 - val_accuracy: 0.7500 - val_loss: 0.3109
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.2858 - val_accuracy: 0.7500 - val_loss: 0.3102
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2859 - val_accuracy: 0.7500 - val_loss: 0.3103
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2861 - val_accuracy: 0.7500 - val_loss: 0.3098
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.2860 - val_accuracy: 0.7500 - val_loss: 0.3100
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2839 - val_accuracy: 0.7500 - val_loss: 0.3094
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2853 - val_accuracy: 0.7500 - val_loss: 0.3085
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2845 - val_accuracy: 0.7500 - val_loss: 0.3086
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2831 - val_accuracy: 0.7500 - val_loss: 0.3079
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2856 - val_accuracy: 0.7500 - val_loss: 0.3073
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2832 - val_accuracy: 0.7500 - val_loss: 0.3066
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.2850 - val_accuracy: 0.7500 - val_loss: 0.3070
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2825 - val_accuracy: 0.7500 - val_loss: 0.3064
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.2805 - val_accuracy: 0.7500 - val_loss: 0.3066
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2831 - val_accuracy: 0.7500 - val_loss: 0.3060
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2802 - val_accuracy: 0.7500 - val_loss: 0.3058
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2826 - val_accuracy: 0.7500 - val_loss: 0.3058
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2795 - val_accuracy: 0.7500 - val_loss: 0.3061
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2818 - val_accuracy: 0.7500 - val_loss: 0.3059
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2805 - val_accuracy: 0.7500 - val_loss: 0.3051
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2798 - val_accuracy: 0.7500 - val_loss: 0.3043
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.2785 - val_accuracy: 0.7500 - val_loss: 0.3036
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2785 - val_accuracy: 0.7500 - val_loss: 0.3027
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2767 - val_accuracy: 0.7500 - val_loss: 0.3029
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2767 - val_accuracy: 0.7500 - val_loss: 0.3022
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.2759 - val_accuracy: 0.7500 - val_loss: 0.3024
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2774 - val_accuracy: 0.7500 - val_loss: 0.3016
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.2771 - val_accuracy: 0.7500 - val_loss: 0.3010
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.2762 - val_accuracy: 0.7500 - val_loss: 0.3010